name: 'ktlintを実行'
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: 現ブランチからチェックアウト
        uses: actions/checkout@v3

      - name: ktlintを実行
        uses: ScaCap/action-ktlint@0.45.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review