name: 'ktlintを実行'
on:
  - pull_request
  - push
  - workflow_dispatch
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: 現ブランチからチェックアウト
        uses: actions/checkout@v3

      - name: ./gradlewに権限を付与
        run: |
          chmod 777 ${{ github.workspace }}/gradlew

      - name: ktlintを実行(gradlew)
        run: |
          ${{ github.workspace }}/gradlew ktlintCheck
