name: 'ktlintを実行'
on: [workflow_dispatch, push, pull_request]
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: 現ブランチからチェックアウト
        uses: actions/checkout@v1

      - name: ktlintを実行
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
