name: 'ktlintを実行'
on:
  - pull_request
  - push
  - workflow_dispatch
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: 現ブランチからチェックアウト
        uses: actions/checkout@v3

      - name: 現ブランチを確認
        run: git branch

      - name: ktlintを実行
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review